import main_menu
import lib_lab
def Lib_Lab() :
    while True:
        print("*********************************************************************************")
        print("*                                     SCHOOL MANAGEMENT SYSTEM                                                  *")
        print("*********************************************************************************")
        print("**----------- LIBRARY $ LAB -----------**")
        print(" 1. LIBRARY :- ")
        print(" 2. LAB :- ")
        print(" 3. Return :- ")
        print("---------------------------------------")
        print(" ")
        a=int(input("Input your Choice:- "))
        if a==1:
            lib_lab.lib_module()
        elif a==2:
            lib_lab.lab_module()
        elif a==3:
            break
        else:
            print("EROOR: Invalid choice ,try again...")
            conti="Press any key to return to main menu.."
def lib_module():
    print("-: You'e in LIBRARY Module :-")
    print("-----------------------------------")
    op=open("booksdetails.txt","r")
    str=op.read()
    print(str)
    print(" ")
    op.close()
    print("1. Buy book :-")
    print("2. Read book :-")
    print(" ")
    z=int(input("Enter your choice:-"))
    print(" ")
    if z==1:
        rang=int(input("How many books you want to buy:-"))
        d=0
        for i in range(rang):
            a=input("Enter book name")
            c=input("Publisher:-")
            b=int(input("Book price:-"))
            d+=b
            print("Book:-",a,"Publisher:-",c,"Price:-",b)
        j=input("Name")
        k=input("Class")
        l=input("Sec")
        print("Name:-",j,", Class:-",k,"Sec:-",l,", Total amount:-",d)
    if z==2:
        a=input("Which book you want to take to read :-")
        b=input("Publisher:-")
        p=input("Book code :-")
        c=input("Date of obtain :-")
        d=input("Date of return :-")
        e=input("Student name :-")
        f=input("Class :-")
        g=input("Sec :-")
        h=input("Mobile no. :-")
        print(" ")
        print("Name:-",e,", Class:-",f,", Sec:-",g,", Mobile no. :-",h,)
        print("Book name:-",a,", Publisher:-",b,", Code:-",p,", DOB:-",c,", DOR:-",d)
def lab_module():
    print(" -: You'e in LAB Module :-")
    print("---------------------------")
    print(" ")
    print("1.Physics Lab:-")
    print("2.Computer Lab:-")
    print("3.Chemistry Lab:-")
    print("4.Biology Lab:-")
    print(" ")
    a=int(input("Enter your required lab:-"))
    print(" ")
    if a==1:
        print(" You are in Physics lab:-")
        print("--=-=-=-=-=-=-=-=-=-=--")
        print(" ")
        b=int(input("Roll no :-"))
        c=input("Name:-")
        d=input("Class:-")
        e=input("Sec:-")
        f=input("Entry time:-")
        g=input("Exit time:-")
        print("Roll no. :-",b,", Name:-",c,", Class:-",d,", Sec:-",e,", Entry time:-",f,", Exit time:-",g)
    if a==2:
        print("You are in Computer lab:-")
        print("--=-=-=-=-=-=-=-=-=-=-=--")
        print(" ")
        b=int(input("Roll no :-"))
        c=input("Name:-")
        d=input("Class:-")
        e=input("Sec:-")
        f=input("Entry time:-")
        g=input("Exit time:-")
        print("Roll no. :-",b,", Name:-",c,", Class:-",d,", Sec:-",e,", Entry time:-",f,", Exit time:-",g)
    if a==3:
        print(" You are in Chemistry lab:-")
        print("--=-=-=-=-=-=-=-=-=-=-=--")
        print(" ")
        b=int(input("Roll no :-"))
        c=input("Name:-")
        d=input("Class:-")
        e=input("Sec:-")
        f=input("Entry time:-")
        g=input("Exit time:-")
        print("Roll no. :-",b,", Name:-",c,", Class:-",d,", Sec:-",e,", Entry time:-",f,", Exit time:-",g)
    if a==4:
        print(" You are in Biology lab:-")
        print("--=-=-=-=-=-=-=-=-=-=--")
        print(" ")
        b=int(input("Roll no :-"))
        c=input("Name:-")
        d=input("Class:-")
        e=input("Sec:-")
        f=input("Entry time:-")
        g=input("Exit time:-")
        print("Roll no. :-",b,", Name:-",c,", Class:-",d,", Sec:-",e,", Entry time:-",f,", Exit time:-",g)
